files: ^python/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: mixed-line-ending
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/pycqa/autoflake
    rev: v1.5.2
    hooks:
      - id: autoflake
  - repo: local
    hooks:
    - id: poetry-check
      name: poetry-check
      entry: bash -c 'cd python && poetry check'
      language: system
      pass_filenames: false
      files: ^python/pyproject.toml$
    - id: poetry-lock
      name: poetry-lock
      entry: bash -c 'cd python && poetry lock'
      language: system
      pass_filenames: false
      files: ^python/pyproject.toml$
